server:
  port: 9090

spring:
  application:
    name: devices
  profiles:
    active: dev
  # Configure Caffeine caching to store the Bucket in-memory
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:phone_info_db
    driver-class-name: org.h2.Driver
    username: test
    password: test

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method

